notifications:
  email: false
language: c 

before_script:
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  - sudo apt-get -qq update

  ## Install doxygen
  - if [ ${BUILD_CATEGORY:-0} = doxygen ] ; then
      sudo add-apt-repository ppa:libreoffice/libreoffice-4-4 -y && sudo apt-get -qq update &&
      sudo apt-get --no-install-suggests --no-install-recommends -qq install doxygen  &&
      doxygen --version ;
    fi
    
    ## Install doxygen
  - if [ ${BUILD_CATEGORY:-0} = cppcheck ] ; then
      sudo apt-get -qq update &&
      sudo apt-get --no-install-suggests --no-install-recommends -qq install cppcheck  &&
      cppcheck --version ;
    fi

  ## Install 32-bit compatibility libraries
  - sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386
      libstdc++5:i386 libstdc++6:i386 libmpc2:i386

  ## Install GCC dependencies
  #- sudo apt-get -qq install libmpc2 libmpc-dev


script:
  - "make -C tests/$BUILD_TYPE all"

env:
  ## This magically kick-off parallel jobs for each of the for the sets
  ## of environment variable defined below
  ## - BUILD_TYPE='doxygen'  BUILD_CATEGORY='doxygen'
  - BUILD_TYPE='cppcheck' BUILD_CATEGORY='cppcheck'
